(()=>{
 // Concise, localized captions over purpose-made conceptual artwork.
 const words={
 de:['Wirtschaftsingenieurwesen','Prozessgestaltung','KI-Lösungen','Wachstum','Wettbewerbsvorteil','Finanzielle Stabilität','Risiko','Trend','Momentum','Bewertung','Bestand','Lieferzeit','Auftragsgenauigkeit','Kosten','Idee','Konzept','Anwendung','Konzeptionelle Darstellung'],
 en:['Industrial engineering','Process design','AI solutions','Growth','Competitive advantage','Financial health','Risk','Trend','Momentum','Valuation','Inventory','Delivery time','Order accuracy','Cost','Idea','Concept','Application','Conceptual illustration'],
 fa:['مهندسی صنایع','طراحی فرایند','راهکارهای هوش مصنوعی','رشد','مزیت رقابتی','سلامت مالی','ریسک','روند','مومنتوم','ارزش‌گذاری','موجودی','زمان تحویل','دقت سفارش','هزینه','ایده','طرح','اپلیکیشن','نمایش مفهومی'],
 ar:['الهندسة الصناعية','تصميم العمليات','حلول الذكاء الاصطناعي','النمو','الميزة التنافسية','الصحة المالية','المخاطر','الاتجاه','الزخم','التقييم','المخزون','وقت التسليم','دقة الطلب','التكلفة','فكرة','تصميم','تطبيق','تصوير مفاهيمي'],
 tr:['Endüstri mühendisliği','Süreç tasarımı','Yapay zekâ çözümleri','Büyüme','Rekabet avantajı','Finansal sağlık','Risk','Trend','Momentum','Değerleme','Envanter','Teslimat süresi','Sipariş doğruluğu','Maliyet','Fikir','Konsept','Uygulama','Kavramsal görsel'],
 it:['Ingegneria gestionale','Progettazione dei processi','Soluzioni IA','Crescita','Vantaggio competitivo','Solidità finanziaria','Rischio','Tendenza','Momentum','Valutazione','Scorte','Tempi di consegna','Precisione degli ordini','Costi','Idea','Concetto','Applicazione','Illustrazione concettuale'],
 fr:['Génie industriel','Conception des processus','Solutions IA','Croissance','Avantage concurrentiel','Santé financière','Risque','Tendance','Momentum','Valorisation','Stock','Délai de livraison','Exactitude des commandes','Coûts','Idée','Concept','Application','Illustration conceptuelle'],
 ko:['산업공학','프로세스 설계','AI 솔루션','성장','경쟁 우위','재무 건전성','위험','추세','모멘텀','가치 평가','재고','배송 시간','주문 정확도','비용','아이디어','구상','앱','개념 이미지'],
 zh:['工业工程','流程设计','人工智能解决方案','增长','竞争优势','财务健康','风险','趋势','动量','估值','库存','交付时间','订单准确率','成本','想法','构想','应用','概念示意'],
 ja:['経営工学','プロセス設計','AIソリューション','成長','競争優位性','財務健全性','リスク','トレンド','モメンタム','企業価値評価','在庫','納期','注文精度','コスト','アイデア','構想','アプリ','コンセプトイメージ'],
 es:['Ingeniería industrial','Diseño de procesos','Soluciones de IA','Crecimiento','Ventaja competitiva','Salud financiera','Riesgo','Tendencia','Momentum','Valoración','Inventario','Tiempo de entrega','Precisión de pedidos','Costes','Idea','Concepto','Aplicación','Ilustración conceptual'],
 sq:['Inxhinieri industriale','Projektim procesesh','Zgjidhje me IA','Rritja','Avantazhi konkurrues','Gjendja financiare','Rreziku','Trendi','Momenti','Vlerësimi','Inventari','Koha e dorëzimit','Saktësia e porosive','Kostoja','Ide','Koncept','Aplikacion','Ilustrim konceptual']};
 const atlasCaptions={"de": ["Prozesslandkarte", "Kennzahlen", "Reifegrad", "Strategie & Entscheidungen"], "en": ["Process map", "Key indicators", "Maturity", "Strategy & decisions"], "fa": ["نقشه فرایندها", "شاخص‌های کلیدی", "بلوغ فرایند", "استراتژی و تصمیم‌گیری"], "ar": ["خريطة العمليات", "المؤشرات الرئيسية", "النضج", "الاستراتيجية والقرارات"], "tr": ["Süreç haritası", "Temel göstergeler", "Olgunluk", "Strateji ve kararlar"], "it": ["Mappa dei processi", "Indicatori chiave", "Maturità", "Strategia e decisioni"], "fr": ["Carte des processus", "Indicateurs clés", "Maturité", "Stratégie et décisions"], "ko": ["프로세스 지도", "핵심 지표", "성숙도", "전략과 의사결정"], "zh": ["流程地图", "关键指标", "成熟度", "战略与决策"], "ja": ["プロセスマップ", "主要指標", "成熟度", "戦略と意思決定"], "es": ["Mapa de procesos", "Indicadores clave", "Madurez", "Estrategia y decisiones"], "sq": ["Harta e proceseve", "Treguesit kryesorë", "Pjekuria", "Strategjia dhe vendimet"]};
 const reduced=matchMedia('(prefers-reduced-motion: reduce)');
 let host,slides=[],index=0,phase=0,timer,remaining=2800,started=0,hover=false,focus=false,lastLanguage='';
 const e=x=>esc(String(x)),path=p=>p+'?lang='+lang;
 function getSlides(){const p=portfolio[lang],r=restaurantCopy[lang],w=words[lang];return [
 {id:'about',title:'Keywan Fakhri',badge:p.aboutNav,url:path('/about/'),cta:p.aboutNav,labels:w.slice(0,3),art:'about'},
 ...['gastlyo','10x','6m','logistics','prozessatlas'].map(id=>{const x=projectRegistry.find(x=>x.id===id);if(!x)return null;const c=id==='gastlyo'?[r[0],r[1]]:projectCopy[lang][x.copy];return {id,title:c[0],badge:p.available,url:path('/projects/'+(id==='gastlyo'?'restaurant':id)+'/'),cta:p.details,art:id,labels:id==='prozessatlas'?atlasCaptions[lang]:id==='gastlyo'?[3,2,1,4,6,0].map(i=>content[lang].services[i][0]):id==='10x'?w.slice(3,7):id==='6m'?[w[7],w[8],w[9],w[6]]:w.slice(10,14)}}).filter(Boolean),
 {id:'future',title:p.labTitle,badge:p.labLabel,url:'#lab',cta:p.details,art:'6m',labels:projectRegistry.filter(x=>x.area==='lab'||x.status!=='available').map(x=>projectCopy[lang][x.copy][0])},
 {id:'custom',title:r[6],badge:p.servicesNav,url:path('/contact/'),cta:p.talk,art:'about',labels:w.slice(14,17)}
 ]}
 function paint(){if(!host)return;const s=slides[index],p=portfolio[lang],w=words[lang];host.innerHTML=`<a class="concept concept-${s.id}" href="${e(s.url)}" aria-label="${e(s.title+' — '+s.cta)}"><div class="concept-top"><span>${e(s.badge)}</span><span class="concept-position" dir="ltr">${String(index+1).padStart(2,'0')} / ${String(slides.length).padStart(2,'0')}</span></div><div class="concept-stage"><img class="concept-art" src="/concepts/${s.art}.png" alt="" decoding="async" fetchpriority="${index===0?'high':'auto'}"><div class="concept-shade"></div><div class="concept-copy"><span class="concept-kicker" dir="ltr">${s.id==='about'?'KEYONE':s.id==='gastlyo'?'SMART RESTAURANT':s.id==='logistics'?'LOGISTICS':s.id==='prozessatlas'?'PROZESSATLAS':s.id==='10x'?'10X':s.id==='6m'?'6M':'KEYONE / LAB'}</span>${s.id==='about'?'<strong class="concept-name" dir="ltr">Keywan<br>Fakhri<span>.</span></strong>':''}<div class="concept-caption"><span class="concept-caption-text">${e(s.labels[phase]||s.title)}</span></div>${s.id==='about'?`<span class="concept-location">${e(p.location)}</span>`:''}<div class="concept-chapters" aria-hidden="true">${s.labels.map((_,i)=>`<i class="${i===phase?'active':''}"></i>`).join('')}</div></div><span class="concept-footnote">${e(w[17])}</span></div><div class="concept-bottom"><h2>${e(s.title)}</h2><span>${e(s.cta)} <b aria-hidden="true">↗</b></span></div></a>`;
 host.classList.toggle('concept-paused',hover||focus||document.hidden||reduced.matches);
 document.querySelectorAll('#project-grid .project-card').forEach(c=>c.classList.toggle('showcase-selected',c.dataset.showcaseId===s.id));
 // Prepare only the next illustration; no embedded websites or visitor tracking.
 const next=slides[(index+1)%slides.length];const img=new Image();img.src='/concepts/'+next.art+'.png';
 }
 function paintCaption(){const s=slides[index],target=host.querySelector('.concept-caption');target.innerHTML=`<span class="concept-caption-text">${e(s.labels[phase])}</span>`;host.querySelectorAll('.concept-chapters i').forEach((n,i)=>n.classList.toggle('active',i===phase))}
 function suspend(){if(timer){remaining=Math.max(0,remaining-(performance.now()-started));clearTimeout(timer);timer=null;}host?.classList.add('concept-paused')}
 function resume(){if(!host||hover||focus||document.hidden||reduced.matches)return;suspend();host.classList.remove('concept-paused');started=performance.now();timer=setTimeout(()=>{timer=null;phase++;if(phase>=slides[index].labels.length){phase=0;index=(index+1)%slides.length;paint()}else paintCaption();remaining=2800;resume()},remaining)}
 window.renderShowcase=function(){host=document.getElementById('showcase');if(!host)return;slides=getSlides();if(lastLanguage!==lang){index=0;phase=0;lastLanguage=lang;}clearTimeout(timer);timer=null;
 if(!host.dataset.bound){host.dataset.bound='1';host.addEventListener('mouseenter',()=>{hover=true;suspend()});host.addEventListener('mouseleave',()=>{hover=false;resume()});host.addEventListener('focusin',()=>{focus=true;suspend()});host.addEventListener('focusout',()=>{focus=false;resume()});}
 document.querySelectorAll('#project-grid .project-card').forEach((card,i)=>{const x=(typeof visibleProjects==='function'?visibleProjects():projectRegistry.filter(x=>x.area==='projects'&&x.status==='available'))[i];if(!x)return;card.dataset.showcaseId=x.id;card.querySelector('.project-mark')?.remove();card.querySelector('.preview-viewport')?.remove();if(!card.querySelector('.project-index'))card.insertAdjacentHTML('afterbegin',`<span class="project-index" dir="ltr">0${i+1} / ${e(x.id==='gastlyo'?'HOSPITALITY':x.id==='logistics'?'OPERATIONS':x.id.toUpperCase())}</span>`);});
 remaining=2800;paint();resume();};
 document.addEventListener('visibilitychange',()=>document.hidden?suspend():resume());reduced.addEventListener('change',()=>{if(reduced.matches)suspend();else resume()});
})();
