import {rankForecasters} from './research-engine.js';
const node=(tag,text,cls)=>{const n=document.createElement(tag);if(text)n.textContent=text;if(cls)n.className=cls;return n;};
const money=v=>new Intl.NumberFormat('en-US',{maximumFractionDigits:2}).format(v);
function link(label,url){const a=node('a',label);a.href=url;a.target='_blank';a.rel='noopener';return a;}
function p(parent,text,cls){parent.append(node('p',text,cls));}
function sourceNote(parent,text){const d=node('details');d.append(node('summary','Source notes (original language)'));const paragraph=node('p',text,'fine');paragraph.setAttribute('data-original','');paragraph.lang='en';paragraph.dir='ltr';d.append(paragraph);parent.append(d);}
function table(headers,rows){const wrap=node('div',null,'table-scroll'),t=node('table'),head=node('thead'),tr=node('tr');headers.forEach(h=>tr.append(node('th',h)));head.append(tr);t.append(head);const body=node('tbody');for(const cells of rows){const r=node('tr');for(const c of cells){const td=node('td');td.append(typeof c==='string'?document.createTextNode(c):c);r.append(td);}body.append(r);}t.append(body);wrap.append(t);return wrap;}
function forecast(r){const n=node('div');if(!r){n.textContent='No 2026 forecast imported';return n;}n.append(link(`$${money(r.forecast)}`,r.source_url));n.append(node('small',`2026 annual average · USD / ${r.unit}`));if(r.low&&r.high)n.append(node('small',`Forecast range: $${money(r.low)}–$${money(r.high)}`));n.append(node('small',`${r.issued_date_kind==='publication_date'?'Published':'Submitted by'} ${r.issued_by}${r.issued_date_kind==='survey_deadline'?' · survey deadline':''}`));if(r.institution)n.append(node('small',`2026 institution: ${r.institution}`));return n;}
export function renderResearch(data,asset,target){
 target.replaceChildren();
 const result=rankForecasters(data,asset.id,new Date(data.reviewed_at));
 const status=node('div',result.ranked.length>=3?`${result.ranked.length} ranked forecasters · five completed years · source-backed records`:result.ranked.length?`${result.ranked.length} evaluated forecasters · fewer than 3 · insufficient peers for ranking`:'Insufficient evidence for a five-year ranking · minimum 3 forecasters',`research-status${result.ranked.length>=3?'':' warning'}`);target.append(status);
 if(result.ranked.length){
  p(target,'Five completed years, 2021–2025. Comparable forecasts are evaluated against actual prices. Lower error is better.','rank-note');
  target.append(table(['Forecaster / rank if comparable','Historical error','2026 forecast'],result.ranked.map((r,i)=>{const who=node('div');who.append(node('strong',`${result.ranked.length>=3?`${i+1}. `:''}${r.forecaster}`));who.append(node('small','5 observations · 2021–2025'));const error=node('div',`${r.error.toFixed(2)}%`);error.append(node('small','Weighted mean absolute percentage error'));return [who,error,forecast(r.latest)];})));
  const evidence=node('details');evidence.append(node('summary','Open five-year evidence and source links'));
  for(const r of result.ranked){const detail=node('details');detail.append(node('summary',r.forecaster));detail.append(table(['Year','Forecast / actual','Error','Evidence'],r.history.map(x=>{const sources=node('div');sources.append(link('Original forecast',x.source_url),document.createTextNode(' · '),link('Actual result',x.actual_source));sources.append(node('small',`${x.issued_date_kind==='publication_bound'?'Published by':x.issued_date_kind==='publication_date'?'Published':'Submitted by'} ${x.issued_by}`));sources.append(link('Verify date',x.date_source));return [String(x.target_year),`$${money(x.forecast)} / $${money(x.actual)}`,`${x.error.toFixed(2)}%`,sources];})));p(detail,`${data.benchmarks[asset.id].basis} · USD / ${data.benchmarks[asset.id].unit}. Employer changes do not merge different analysts.`);evidence.append(detail);}target.append(evidence);
  const pending=result.excluded.filter(r=>r.latest);
  if(pending.length){const d=node('details');d.append(node('summary',`${pending.length} other current forecasters · not ranked`));p(d,'These analysts lack five complete, comparable observations in the imported history. Their forecasts are not assigned an accuracy rank.');d.append(table(['Forecaster','History imported','2026 forecast'],pending.map(r=>[r.forecaster,`${r.years} / 5 years`,forecast(r.latest)])));target.append(d);}
 }else{sourceNote(target,data.coverage[asset.id].note);if(asset.category==='ETFs')p(target,'An index outlook, gold forecast or long-term asset-class return assumption is not a forecast of this ETF’s share price. These are not converted into ETF accuracy scores.');}
 const contexts=(data.context_forecasts||[]).filter(r=>r.asset_id===asset.id);
 if(contexts.length){target.append(node('h3','Published forecasts · historical accuracy unverified'));p(target,'Annual average is not a year-end price. Missing forecasts are not estimated. Historical error does not guarantee future accuracy.','rank-note');for(const r of contexts){const c=node('div',null,'forecast-card');c.append(node('strong',r.provider),link(`$${money(r.forecast)} USD / ${r.unit}`,r.source_url));p(c,r.basis);p(c,`${r.date_kind==='survey_month'?'Survey month':'Published'}: ${r.issued_by} · imported ${data.reviewed_at.replace('T',' ').replace('Z',' UTC')}`,'fine');sourceNote(c,r.note);target.append(c);}}
 if(asset.category==='ETFs'){const d=node('details');d.append(node('summary','Primary research context · not ETF price forecasts'));d.append(link('Vanguard capital market forecasts','https://corporate.vanguard.com/content/corporatesite/us/en/corp/vemo/vemo-return-forecasts.html'));p(d,'Long-term asset-class return expectations. No claim of exact ETF forecast accuracy.');d.append(link('BlackRock capital market assumptions','https://www.blackrock.com/institutions/en-us/insights/thought-leadership/capital-market-assumptions'));target.append(d);}
 if(!result.ranked.length&&!contexts.length)p(target,'No current numeric forecast has been verified and imported for this asset. Coverage remains open; no placeholder target is shown.','status');
}
export function renderMethodology(data,target){
 p(target,'Five completed years, 2021–2025. Comparable forecasts are evaluated against actual prices. Lower error is better.');
 p(target,'Weighted mean absolute percentage error');
 const formula=node('p','Σ(weight × |forecast − actual| / actual × 100)');formula.setAttribute('data-original','');formula.dir='ltr';target.append(formula);
 p(target,'Year weights: 2021 9%, 2022 13%, 2023 18%, 2024 25%, 2025 35%. These chosen weights emphasize recent years.');
 p(target,'At least 3 and at most 10 comparable forecasters are required for a ranked comparison. Available evidence is retained separately; no names are invented to fill the minimum.');
 p(target,'Annual average is not a year-end price. Missing forecasts are not estimated. Historical error does not guarantee future accuracy.');
 sourceNote(target,[data.methodology.scope,data.methodology.metric,data.methodology.selection,...data.methodology.limitations].join(' '));
 target.append(link('Download the factual evidence snapshot','./evidence.json'));
}
